name: prepare credentials for poetry
description: prepares credentials for poetry to push/pull to/from a private package registry
inputs:
  token:
    description: api token
    default: ""
runs:
  using: composite
  steps:
  - id: login_to_registry
    shell: bash
    run: |
      set +x
      poetry config pypi-token.pypi ${{ inputs.token }}
