name: check for directories containing changes
description: indicate whether or not a given path has changes
inputs:
  path-prefix:
    description: path prefix to directories, including the final preceding slash (eg. /src/project/)
    default: ""
  include:
    description: glob pattern used to include files, space delimited for multiple patterns
    default: ""
  exclude:
    description: glob pattern used to exclude files, space delimited for multiple patterns
    default: ""
  include-hidden:
    description: include hidden directories
    default: false
  base-branch:
    description: base branch against which to compare current revision
    default: main
  compare-tag: 
    description: tag against which to compare current revision
    default: base
outputs:
  directories:
    description: json list of all directories containing changes
    value: ${{ steps.get_changed_directories.outputs.directories }}
  names:
    description: json list of all directory names containing changes, only the final name in the path
    value: ${{ steps.get_changed_directories.outputs.names }}
  is-merged:
    description: returns true if the changes are merged to the base branch
    value: ${{ steps.determine_merge_state.outputs.is-merged }}
runs:
  using: composite
  steps:
  - id: determine_merge_state
    shell: bash
    run: |
      if [ ${{ github.ref }} == refs/heads/${{ inputs.base-branch }} ]
      then
        printf is-merged=true >> $GITHUB_OUTPUT
      else
        printf is-merged=false >> $GITHUB_OUTPUT
      fi
    
  - name: ensure existance of compare tag
    shell: bash
    run: |
      LINES=$(git tag -l ${{ inputs.compare-tag }} | wc --lines)
      if [ "$LINES" == "0" ]
      then
        echo "compare tag doesn't exist yet"
        echo "COMPARE_TAG_EXISTS=0" >> $GITHUB_ENV
        echo "BASE_SHA=$(git rev-parse origin/${{ inputs.base-branch }})" >> $GITHUB_ENV
      else
        echo "compare tag exists"
        echo "COMPARE_TAG_EXISTS=1" >> $GITHUB_ENV
      fi
  - name: create compare tag
    if: env.COMPARE_TAG_EXISTS == '0'
    uses: actions/github-script@v7
    with:
      script: |
        github.rest.git.createRef({
          owner: context.repo.owner,
          repo: context.repo.repo,
          ref: "refs/tags/${{ inputs.compare-tag }}",
          sha: "${{ env.BASE_SHA }}"
        })
  - id: get_changed_directories
    name: get changed directories
    shell: bash
    run: |
      DATA=$(git diff --name-only origin/${{ inputs.base-branch }} ${{ github.sha }} | $GITHUB_ACTION_PATH/scripts/get_changed_directories.sh "${{ inputs.base_path }}" "${{ inputs.include }}" "${{ inputs.exclude }}" "${{ inputs.include-hidden }}")
      printf directories=$(echo $DATA | jq -cs .directories) >> $GITHUB_OUTPUT
      printf names=$(echo $DATA | jq -cs .names) >> $GITHUB_OUTPUT
