name: execute integration tasks

on:
  push:
    branches:
    - "**"

jobs:
  evaluate-changed-items:
    runs-on: ubuntu-22.04
    name: Evaluate changed items
    outputs:
      directories: ${{ steps.check-changes.outputs.directories }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: check-changes
      uses: hashibuto/github-actions/changes-check@test
      with:
        base_branch: master

  execute_integration_tasks:
    strategy: 
      matrix:
        directory: ${{ fromJson(needs.evaluate-changed-items.outputs.directories) }}  
    defaults:
      run:
        working-directory:
          ${{ matrix.directory }}
    runs-on: ubuntu-22.04
    if: needs.evaluate-changed-items.outputs.directories != '[]'
    name: Running
    needs: evaluate-changed-items
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - id: check-version
      uses: hashibuto/github-actions/version-check@test
      with:
        path-prefix: ${{ matrix.directory }}

    - name: Execute tests
      shell: bash
      run: make test